/**
 * Group Academy â€” Agents Domain Export Engine (Barrel)
 */
export { AGENT_REGISTRY, AGENT_BY_ID, getAgent, AgentChatScreen } from "./registry";
export type { AgentScope, AgentRegistryEntry } from "./registry";

// â”€â”€â”€ STAGE 1: EDGE NETWORK LAYER WRAPPERS (API) â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
export {
  agentRuntime,
  aiGeneralChat,
  adminSupportAssistant,
  aiSupportAssistant,
  agentBlueprint,
  ingestAgentKnowledge,
  agentEventDispatcher,
  companyAgentTools,
  triggerAgentPitch,
} from "./api/agentsApi";

// â”€â”€â”€ STAGE 2: HARDENED POSTGRES INFRASTRUCTURE (REPO) â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
// Exporting the full repository suite for clean component consumption
export {
  updateAiAgent,
  insertAiAgent,
  deactivateAiAgent,
  toggleAiAgentActive,
  insertNotification,
  getAgentsOverview,
  getStudioBundle,
  deleteAgentKnowledgeSource,
  listAgentsForInsights,
  listAgentCreditEvents,
  listRecentAgentOutreach,
  getTriggersBundle,
  insertAgentTrigger,
  toggleAgentTrigger,
  deleteAgentTrigger,
  updateHeadlessPoolBalance,
  updateHeadlessPoolMonthlyCap,
  listPayoutRequestsByStatus,
  markPayoutPaid,
  updatePayoutRequestStatus,
  listAgentReviews,
  upsertAgentReview,
  createAgentChatSession,
  updateAgentChatSession,
  updateAgentChatSessionMessages,
  getAgentChatSession,
  getAgentCreditCost,
  deductCredits,
  deleteAgentMessage,
  updateAgentThread,
  bumpAgentThreadLastMessage,
  insertAgentMessage,
  countAiAgentsByTemplateFlag,
  listAiAgentsForFleet,
  listAiAgentsCompact,
  getAiAgentById,
  cloneAiAgentInstance,
  listAiAgentInstancesMinimal,
  incrementAgentConversations,
  getAgentByKey,
  listPinnedAgentKeys,
  getTalentMarketplaceSummary,
  isAgentConnected,
  connectAgent,
  listAgentChannels,
  listAllAgentTools,
  listAiAgentsForListTab,
  listRecentAgentChatSessions,
  listAgentKnowledgeSources,
  listAdminAgentBasics,
  listAgentsByMarketplaceStatus,
  listAllAgentsOrdered,
  listAgentChatSessionKeys,
  listRecentAgentOutreachAdmin,
  countAgentOutreachDedupeSince,
  countPlatformEventsSince,
  listTalentAgentChatSessionKeys,
  listTopActiveAgentsForQuickActions,
} from "./repo/agentsRepo";

// â”€â”€â”€ STAGE 3: BOUND INTEGRATION SCHEMA TYPE DEFINITIONS â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
export type {
  AgentRuntimeRequest,
  AgentRuntimeResponse,
  AiGeneralChatRequest,
  AiGeneralChatResponse,
  AdminSupportAssistantRequest,
  AdminSupportAssistantResponse,
  AiSupportAssistantRequest,
  AiSupportAssistantResponse,
  AgentBlueprintRequest,
  AgentBlueprintProposal,
  AgentBlueprintResponse,
  IngestAgentKnowledgeRequest,
  IngestAgentKnowledgeResponse,
  AgentEventDispatcherRequest,
  AgentEventDispatcherResponse,
  CompanyAgentToolsRequest,
  CompanyAgentToolsResponse,
  TriggerAgentPitchRequest,
  TriggerAgentPitchResponse,
} from "@/edge/contracts/agents";

