export {
  getHrGraphMaster,
  getHrOnboardingMaster,
  getHrPayrollMaster,
  getWorkforceDashboard,
  listHrTargets,
  upsertHrTarget,
  deleteHrTarget,
  listActiveWorkforceMembersWithName,
  searchTalentsByNameOrEmail,
  insertWorkforceMember,
  updateWorkforceMember,
  getWorkforceMembersForCompany,
  getMyWorkforceAssignment,
  listWorkforceChannelConnections,
  listWorkforceRoutingRules,
  upsertWorkforceChannelConnection,
  upsertWorkforceRoutingRule,
  deleteWorkforceChannelConnection,
  deleteWorkforceRoutingRule,
} from "../repo/workforceRepo";

