import { useParams, Link } from "react-router-dom";
import { Helmet } from "react-helmet-async";
import { ArrowRight, CheckCircle2, Star, Zap, Clock, Users, Target, TrendingUp, FileText, Mic, DollarSign, Briefcase } from "lucide-react";
import { Button } from "@/components/ui/button";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";

const SERVICES: Record<string, {
  title: string;
  tagline: string;
  description: string;
  metaDescription: string;
  icon: React.ReactNode;
  benefits: string[];
  howItWorks: { step: string; desc: string }[];
  cta: string;
  ctaLink: string;
  color: string;
  jsonLdType: string;
}> = {
  "career-assessment": {
    title: "AI Career Readiness Scorecard",
    tagline: "Decode your career potential with AI-powered assessment",
    description: "Get a comprehensive analysis of your career readiness across key competency areas. Our AI evaluates your skills, experience, and market positioning to generate a personalized scorecard with actionable recommendations.",
    metaDescription: "Free AI-powered Career Readiness Scorecard. Assess your skills, get personalized recommendations, and benchmark against industry standards. By GroUp Academy.",
    icon: <Target className="h-8 w-8" />,
    benefits: [
      "Comprehensive skill gap analysis across 6 competency areas",
      "Personalized improvement roadmap with actionable steps",
      "Industry benchmarking against market standards",
      "Downloadable PDF scorecard to track progress",
      "AI-generated career path recommendations",
    ],
    howItWorks: [
      { step: "Select Your Profession", desc: "Choose from 30+ career tracks" },
      { step: "Answer Assessment Questions", desc: "Complete targeted questions in 10-15 minutes" },
      { step: "Get Your AI Scorecard", desc: "Receive a detailed career readiness report" },
    ],
    cta: "Take Free Assessment",
    ctaLink: "/career-assessment",
    color: "primary",
    jsonLdType: "Service",
  },
  "mock-interview": {
    title: "AI Mock Interview Practice",
    tagline: "Practice with AI and ace your next interview",
    description: "Prepare for real interviews with AI-generated questions tailored to your target role and experience level. Get detailed feedback on your answers, body language tips, and a performance breakdown.",
    metaDescription: "AI Mock Interview Practice — role-specific questions, instant AI feedback, and detailed performance analysis. Prepare with GroUp Academy.",
    icon: <Mic className="h-8 w-8" />,
    benefits: [
      "Role-specific interview questions generated by AI",
      "Detailed answer analysis with improvement suggestions",
      "Performance scoring across communication & technical skills",
      "Practice for behavioral, technical, and situational rounds",
      "Downloadable interview prep report",
    ],
    howItWorks: [
      { step: "Choose Your Role", desc: "Select position type and experience level" },
      { step: "Answer Interview Questions", desc: "Respond to AI-curated questions" },
      { step: "Get AI Feedback", desc: "Receive a detailed performance analysis" },
    ],
    cta: "Start Mock Interview",
    ctaLink: "/mock-interview",
    color: "secondary",
    jsonLdType: "Service",
  },
  "salary-analysis": {
    title: "AI Salary Analysis & Benchmarking",
    tagline: "Know your worth with data-driven salary insights",
    description: "Get AI-powered salary benchmarking based on your role, experience, skills, and market data. Understand your market value and negotiate with confidence.",
    metaDescription: "AI Salary Analysis & Benchmarking — know your market value. Data-driven salary insights for Bangladesh and global markets. By GroUp Academy.",
    icon: <DollarSign className="h-8 w-8" />,
    benefits: [
      "Market-rate salary benchmarking for your specific role",
      "Experience-adjusted compensation analysis",
      "Skill-premium identification for higher earnings",
      "Negotiation talking points and strategy",
      "Industry and location-based comparisons",
    ],
    howItWorks: [
      { step: "Enter Your Details", desc: "Role, experience, skills, and location" },
      { step: "AI Analyzes Market Data", desc: "Cross-references salary databases" },
      { step: "Get Salary Report", desc: "Detailed benchmarking with negotiation tips" },
    ],
    cta: "Analyze My Salary",
    ctaLink: "/salary-analysis",
    color: "accent",
    jsonLdType: "Service",
  },
  "portfolio": {
    title: "AI Digital Portfolio Builder",
    tagline: "Showcase your career story with a professional portfolio",
    description: "Let AI help you build a stunning digital portfolio that highlights your skills, projects, and achievements. Perfect for job applications, freelancing, and personal branding.",
    metaDescription: "AI Digital Portfolio Builder — create a professional online portfolio. Showcase skills, projects, and achievements. Built by GroUp Academy.",
    icon: <Briefcase className="h-8 w-8" />,
    benefits: [
      "AI-curated content from your CV and profile",
      "Professional responsive design templates",
      "Shareable public URL for job applications",
      "Integrated project showcase and skill highlights",
      "Easy updates without any coding",
    ],
    howItWorks: [
      { step: "Upload Your CV", desc: "Or fill in your career details" },
      { step: "AI Builds Your Portfolio", desc: "Generates content and layout" },
      { step: "Review & Share", desc: "Get a shareable link instantly" },
    ],
    cta: "Build My Portfolio",
    ctaLink: "/portfolio-request",
    color: "primary",
    jsonLdType: "Service",
  },
};

export default function ServiceLanding() {
  const { serviceSlug } = useParams<{ serviceSlug: string }>();
  const service = serviceSlug ? SERVICES[serviceSlug] : null;

  if (!service) {
    return (
      <div className="min-h-screen bg-background">
        <Navbar />
        <div className="max-w-4xl mx-auto px-4 py-20 text-center">
          <h1 className="text-2xl font-bold text-foreground mb-4">Service Not Found</h1>
          <p className="text-muted-foreground mb-6">The service you're looking for doesn't exist.</p>
          <Link to="/services">
            <Button>View All Services</Button>
          </Link>
        </div>
        <Footer />
      </div>
    );
  }

  const jsonLd = {
    "@context": "https://schema.org",
    "@type": service.jsonLdType,
    name: service.title,
    description: service.description,
    provider: {
      "@type": "EducationalOrganization",
      name: "GroUp Academy",
      url: "https://groupacademy.lovable.app",
    },
    areaServed: { "@type": "Country", name: "Bangladesh" },
    serviceType: "Career Development",
  };

  return (
    <div className="min-h-screen bg-background">
      <Helmet>
        <title>{service.title} | GroUp Academy</title>
        <meta name="description" content={service.metaDescription} />
        <link rel="canonical" href={`https://groupacademy.lovable.app/service/${serviceSlug}`} />
        <meta property="og:title" content={`${service.title} | GroUp Academy`} />
        <meta property="og:description" content={service.metaDescription} />
        <meta property="og:type" content="website" />
        <script type="application/ld+json">{JSON.stringify(jsonLd)}</script>
      </Helmet>

      <Navbar />

      {/* Hero */}
      <section className="relative overflow-hidden py-20 md:py-28">
        <div className="absolute inset-0 bg-gradient-to-br from-primary/5 via-background to-secondary/5" />
        <div className="relative max-w-4xl mx-auto px-4 text-center">
          <div className="inline-flex items-center justify-center w-16 h-16 rounded-2xl bg-primary/10 text-primary mb-6">
            {service.icon}
          </div>
          <h1 className="text-3xl md:text-5xl font-extrabold text-foreground mb-4 leading-tight">
            {service.title}
          </h1>
          <p className="text-lg md:text-xl text-muted-foreground mb-8 max-w-2xl mx-auto">
            {service.tagline}
          </p>
          <div className="flex flex-col sm:flex-row gap-3 justify-center">
            <Link to={service.ctaLink}>
              <Button size="lg" className="rounded-xl text-base px-8">
                {service.cta}
                <ArrowRight className="ml-2 h-5 w-5" />
              </Button>
            </Link>
            <Link to="/auth?returnTo=/app/services">
              <Button variant="outline" size="lg" className="rounded-xl text-base px-8">
                Sign Up Free
              </Button>
            </Link>
          </div>
        </div>
      </section>

      {/* Benefits */}
      <section className="py-16 bg-muted/30">
        <div className="max-w-4xl mx-auto px-4">
          <h2 className="text-2xl md:text-3xl font-bold text-foreground text-center mb-10">
            What You Get
          </h2>
          <div className="grid gap-4 md:grid-cols-2">
            {service.benefits.map((benefit, i) => (
              <div key={i} className="flex items-start gap-3 bg-card rounded-xl p-4 border border-border">
                <CheckCircle2 className="h-5 w-5 text-accent shrink-0 mt-0.5" />
                <span className="text-sm text-foreground">{benefit}</span>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* How it Works */}
      <section className="py-16">
        <div className="max-w-4xl mx-auto px-4">
          <h2 className="text-2xl md:text-3xl font-bold text-foreground text-center mb-10">
            How It Works
          </h2>
          <div className="grid gap-6 md:grid-cols-3">
            {service.howItWorks.map((step, i) => (
              <div key={i} className="text-center">
                <div className="w-12 h-12 rounded-full bg-primary/10 text-primary font-bold text-lg flex items-center justify-center mx-auto mb-4">
                  {i + 1}
                </div>
                <h3 className="font-semibold text-foreground mb-2">{step.step}</h3>
                <p className="text-sm text-muted-foreground">{step.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="py-16 bg-gradient-to-r from-primary/10 to-secondary/10">
        <div className="max-w-2xl mx-auto px-4 text-center">
          <h2 className="text-2xl font-bold text-foreground mb-4">Ready to Get Started?</h2>
          <p className="text-muted-foreground mb-6">
            Join thousands of professionals using GroUp Academy to accelerate their careers.
          </p>
          <Link to={service.ctaLink}>
            <Button size="lg" className="rounded-xl text-base px-10">
              {service.cta}
              <ArrowRight className="ml-2 h-5 w-5" />
            </Button>
          </Link>
        </div>
      </section>

      <Footer />
    </div>
  );
}
