-- Migration to seed the 9 canonical talent agents into the ai_agents table
-- Target Table: public.ai_agents
-- Handled Idempotently via ON CONFLICT (agent_key)

INSERT INTO public.ai_agents (
    agent_key,
    name,
    description,
    icon,
    color,
    bg_color,
    expertise_areas,
    is_active,
    credit_cost,
    category,
    agent_type,
    is_featured,
    system_prompt,
    message_credit_cost,
    connection_fee,
    visibility,
    marketplace_status,
    allowed_tools,
    active_prompt_variant,
    prompt_variants,
    personality_traits,
    audience,
    builder_model,
    model,
    kill_switch,
    canvas_mode,
    default_channel
) VALUES
(
    'ai-general',
    'AI General',
    'Your ultimate platform guide',
    'Sparkles',
    'text-blue-600',
    'bg-gradient-to-r from-blue-500/10 to-purple-500/10',
    ARRAY['Platform Guide', 'Feature Discovery', 'Agent Routing'],
    true,
    1,
    'general',
    'talent',
    true,
    'You are AI General, the platform concierge. Guide users to features, agents, and content.',
    1,
    0,
    'public',
    'approved',
    ARRAY[]::text[],
    'default',
    '{}'::jsonb,
    '{}'::jsonb,
    'talent',
    'gpt-4o',
    'gpt-4o',
    false,
    'none',
    'chat'
),
(
    'career-consultant',
    'Career Consultant',
    'Plan your professional journey',
    'Briefcase',
    'text-blue-600',
    'bg-blue-500/10',
    ARRAY['Career Planning', 'Job Search', 'Career Change'],
    true,
    1,
    'career',
    'talent',
    true,
    'You are an expert Career Consultant. Help the user plan their career path.',
    1,
    0,
    'public',
    'approved',
    ARRAY[]::text[],
    'default',
    '{}'::jsonb,
    '{}'::jsonb,
    'talent',
    'gpt-4o',
    'gpt-4o',
    false,
    'none',
    'chat'
),
(
    'cv-coach',
    'CV Coach',
    'Optimize your resume',
    'FileText',
    'text-emerald-600',
    'bg-emerald-500/10',
    ARRAY['CV Review', 'ATS Optimization', 'Cover Letters'],
    true,
    1,
    'career',
    'talent',
    true,
    'You are an expert CV Coach. Review resumes and suggest improvements for ATS.',
    1,
    0,
    'public',
    'approved',
    ARRAY[]::text[],
    'default',
    '{}'::jsonb,
    '{}'::jsonb,
    'talent',
    'gpt-4o',
    'gpt-4o',
    false,
    'none',
    'chat'
),
(
    'interview-coach',
    'Interview Coach',
    'Ace your interviews',
    'Mic',
    'text-purple-600',
    'bg-purple-500/10',
    ARRAY['Mock Practice', 'STAR Method', 'Confidence'],
    true,
    1,
    'career',
    'talent',
    true,
    'You are an expert Interview Coach. Conduct mock interviews and provide feedback.',
    1,
    0,
    'public',
    'approved',
    ARRAY[]::text[],
    'default',
    '{}'::jsonb,
    '{}'::jsonb,
    'talent',
    'gpt-4o',
    'gpt-4o',
    false,
    'none',
    'chat'
),
(
    'salary-negotiator',
    'Salary Negotiator',
    'Negotiate better offers',
    'DollarSign',
    'text-amber-600',
    'bg-amber-500/10',
    ARRAY['Negotiation', 'Market Rates', 'Benefits'],
    true,
    1,
    'career',
    'talent',
    true,
    'You are an expert Salary Negotiator. Help users maximize their compensation.',
    1,
    0,
    'public',
    'approved',
    ARRAY[]::text[],
    'default',
    '{}'::jsonb,
    '{}'::jsonb,
    'talent',
    'gpt-4o',
    'gpt-4o',
    false,
    'none',
    'chat'
),
(
    'ielts-tutor',
    'IELTS Tutor',
    'Master English tests',
    'BookOpen',
    'text-rose-600',
    'bg-rose-500/10',
    ARRAY['Speaking', 'Writing', 'Test Strategies'],
    true,
    1,
    'study_abroad',
    'talent',
    true,
    'You are an expert IELTS Tutor. Help users prepare for the IELTS exam.',
    1,
    0,
    'public',
    'approved',
    ARRAY[]::text[],
    'default',
    '{}'::jsonb,
    '{}'::jsonb,
    'talent',
    'gpt-4o',
    'gpt-4o',
    false,
    'none',
    'chat'
),
(
    'skill-advisor',
    'Skill Advisor',
    'Learn in-demand skills',
    'Lightbulb',
    'text-teal-600',
    'bg-teal-500/10',
    ARRAY['Skill Gaps', 'Learning Paths', 'Industry Trends'],
    true,
    1,
    'career',
    'talent',
    true,
    'You are an expert Skill Advisor. Recommend learning paths and skills.',
    1,
    0,
    'public',
    'approved',
    ARRAY[]::text[],
    'default',
    '{}'::jsonb,
    '{}'::jsonb,
    'talent',
    'gpt-4o',
    'gpt-4o',
    false,
    'none',
    'chat'
),
(
    'study-abroad-advisor',
    'Study Abroad Advisor',
    'Plan your international education',
    'GraduationCap',
    'text-cyan-600',
    'bg-cyan-500/10',
    ARRAY['University Selection', 'Visa Guidance', 'Scholarships', 'Country Comparison'],
    true,
    1,
    'study_abroad',
    'talent',
    true,
    'You are an expert Study Abroad Advisor. Help users choose universities, navigate visa processes, and find scholarships for international education.',
    1,
    0,
    'public',
    'approved',
    ARRAY[]::text[],
    'default',
    '{}'::jsonb,
    '{}'::jsonb,
    'talent',
    'gpt-4o',
    'gpt-4o',
    false,
    'none',
    'chat'
),
(
    'mental-wellness-coach',
    'Mental Wellness Coach',
    'Manage stress and find balance',
    'Heart',
    'text-pink-600',
    'bg-pink-500/10',
    ARRAY['Stress Management', 'Mindfulness', 'Work-Life Balance', 'Burnout Prevention'],
    true,
    1,
    'wellness',
    'talent',
    true,
    'You are a Mental Wellness Coach. Help users manage work stress and find balance.',
    1,
    0,
    'public',
    'approved',
    ARRAY[]::text[],
    'default',
    '{}'::jsonb,
    '{}'::jsonb,
    'talent',
    'gpt-4o',
    'gpt-4o',
    false,
    'none',
    'chat'
)
ON CONFLICT (agent_key) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    icon = EXCLUDED.icon,
    color = EXCLUDED.color,
    bg_color = EXCLUDED.bg_color,
    expertise_areas = EXCLUDED.expertise_areas,
    is_active = EXCLUDED.is_active,
    category = EXCLUDED.category,
    system_prompt = EXCLUDED.system_prompt,
    message_credit_cost = EXCLUDED.message_credit_cost,
    connection_fee = EXCLUDED.connection_fee,
    visibility = EXCLUDED.visibility,
    marketplace_status = EXCLUDED.marketplace_status,
    allowed_tools = EXCLUDED.allowed_tools,
    active_prompt_variant = EXCLUDED.active_prompt_variant,
    prompt_variants = EXCLUDED.prompt_variants,
    personality_traits = EXCLUDED.personality_traits,
    audience = EXCLUDED.audience,
    builder_model = EXCLUDED.builder_model,
    model = EXCLUDED.model,
    kill_switch = EXCLUDED.kill_switch,
    canvas_mode = EXCLUDED.canvas_mode,
    default_channel = EXCLUDED.default_channel;
