-- Migration to add review_notes column and seed the 9 canonical talent agents into public.ai_agents
-- Handled idempotently to ensure sandbox environment databases are populated correctly

ALTER TABLE public.ai_agents
  ADD COLUMN IF NOT EXISTS review_notes text;

INSERT INTO public.ai_agents (
  agent_key,
  name,
  description,
  system_prompt,
  icon,
  color,
  bg_color,
  expertise_areas,
  is_active,
  display_order,
  agent_type,
  owner_kind,
  visibility,
  marketplace_status,
  message_credit_cost,
  connection_fee,
  credit_cost,
  is_featured,
  category
) VALUES
  (
    'ai-general',
    'AI General',
    'Your ultimate platform guide',
    'You are AI General, the platform concierge. Guide users to features, agents, and content.',
    'sparkles',
    'text-blue-600',
    'bg-gradient-to-r from-blue-500/10 to-purple-500/10',
    ARRAY['Platform Guide','Feature Discovery','Agent Routing'],
    true,
    1,
    'talent',
    'platform',
    'public',
    'approved',
    0,
    0,
    0,
    true,
    'general'
  ),
  (
    'career-consultant',
    'Career Consultant',
    'Plan your professional journey',
    'You are an expert Career Consultant. Help the user plan their career path.',
    'briefcase',
    'text-blue-600',
    'bg-blue-500/10',
    ARRAY['Career Planning','Job Search','Career Change'],
    true,
    2,
    'talent',
    'platform',
    'public',
    'approved',
    1,
    0,
    1,
    true,
    'career'
  ),
  (
    'cv-coach',
    'CV Coach',
    'Optimize your resume',
    'You are an expert CV Coach. Review resumes and suggest improvements for ATS.',
    'file-text',
    'text-emerald-600',
    'bg-emerald-500/10',
    ARRAY['CV Review','ATS Optimization','Cover Letters'],
    true,
    3,
    'talent',
    'platform',
    'public',
    'approved',
    1,
    0,
    1,
    true,
    'career'
  ),
  (
    'interview-coach',
    'Interview Coach',
    'Ace your interviews',
    'You are an expert Interview Coach. Conduct mock interviews and provide feedback.',
    'mic',
    'text-purple-600',
    'bg-purple-500/10',
    ARRAY['Mock Practice','STAR Method','Confidence'],
    true,
    4,
    'talent',
    'platform',
    'public',
    'approved',
    1,
    0,
    1,
    false,
    'career'
  ),
  (
    'salary-negotiator',
    'Salary Negotiator',
    'Negotiate better offers',
    'You are an expert Salary Negotiator. Help users maximize their compensation.',
    'dollar-sign',
    'text-amber-600',
    'bg-amber-500/10',
    ARRAY['Negotiation','Market Rates','Benefits'],
    true,
    5,
    'talent',
    'platform',
    'public',
    'approved',
    1,
    0,
    1,
    false,
    'career'
  ),
  (
    'ielts-tutor',
    'IELTS Tutor',
    'Master English tests',
    'You are an expert IELTS Tutor. Help users prepare for the IELTS exam.',
    'book-open',
    'text-rose-600',
    'bg-rose-500/10',
    ARRAY['Speaking','Writing','Test Strategies'],
    true,
    6,
    'talent',
    'platform',
    'public',
    'approved',
    1,
    0,
    1,
    false,
    'abroad'
  ),
  (
    'skill-advisor',
    'Skill Advisor',
    'Learn in-demand skills',
    'You are an expert Skill Advisor. Recommend learning paths and skills.',
    'lightbulb',
    'text-teal-600',
    'bg-teal-500/10',
    ARRAY['Skill Gaps','Learning Paths','Industry Trends'],
    true,
    7,
    'talent',
    'platform',
    'public',
    'approved',
    1,
    0,
    1,
    false,
    'learning'
  ),
  (
    'study-abroad-advisor',
    'Study Abroad Advisor',
    'Plan your international education',
    'You are an expert Study Abroad Advisor. Help users choose universities, navigate visa processes, and find scholarships for international education.',
    'graduation-cap',
    'text-cyan-600',
    'bg-cyan-500/10',
    ARRAY['University Selection','Visa Guidance','Scholarships'],
    true,
    8,
    'talent',
    'platform',
    'public',
    'approved',
    1,
    0,
    1,
    false,
    'abroad'
  ),
  (
    'mental-wellness-coach',
    'Mental Wellness Coach',
    'Manage stress and find balance',
    'You are a Mental Wellness Coach. Help users manage work stress and find balance.',
    'heart',
    'text-pink-600',
    'bg-pink-500/10',
    ARRAY['Stress Management','Mindfulness','Work-Life Balance'],
    true,
    9,
    'talent',
    'platform',
    'public',
    'approved',
    1,
    0,
    1,
    false,
    'wellness'
  )
ON CONFLICT (agent_key) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  system_prompt = EXCLUDED.system_prompt,
  icon = EXCLUDED.icon,
  color = EXCLUDED.color,
  bg_color = EXCLUDED.bg_color,
  expertise_areas = EXCLUDED.expertise_areas,
  is_active = true,
  agent_type = 'talent',
  owner_kind = 'platform',
  visibility = 'public',
  marketplace_status = 'approved',
  message_credit_cost = EXCLUDED.message_credit_cost,
  connection_fee = EXCLUDED.connection_fee,
  credit_cost = EXCLUDED.credit_cost,
  is_featured = EXCLUDED.is_featured,
  category = EXCLUDED.category,
  display_order = EXCLUDED.display_order,
  updated_at = now();
